### ISSUE TITLE
Provide questions for survey

### ISSUE THREAD

**Issue by akshay-vaidya** [andrewkshim/surveymonty#11]
How do I create questions for a survey using this code?

**Comment by andrewkshim** [comment]
Hi @akshay-vaidya, you can find the list of the supported V3 API calls in the [V3 JSON config file](https://github.com/andrewkshim/surveymonty/blob/master/surveymonty/versions/v3.json). The library parses that JSON in order to create the API methods on the `surveymonty.Client` object.

In particular, there's a `create_survey_page_question` method on the client that might be relevant to your use case. [Here's the same V3 JSON config but linked to the section for `create_survey_page_question`](https://github.com/andrewkshim/surveymonty/blob/master/surveymonty/versions/v3.json#L108).

In code, this would look like:
```
client = surveymonty.Client("YOUR_API_KEY")
client.create_survey_page_question(
    "survey_id",
    "page_id",
    json="the json payload for your request"
)
```

That `json` keyword argument is the exact same as the one in the [`requests` library](http://docs.python-requests.org/en/master/). You can pass in any keyword argument into the `suruveymonty.Client` API methods that the `requests` library accepts.

**Comment by akshay-vaidya** [comment]
Thanks for your comments. I tried using the JSON payload for proving image as a question (payload for presentation). It gives me Response 400. I am thinking the JSON part has some syntax error.  Kindly help.

**Comment by andrewkshim** [comment]
@akshay-vaidya can you provide a code sample and the error message you're seeing?

**Comment by akshay-vaidya** [comment]
@andrewkshim 
Code: 
client.create_survey_page_question(
    survey_id,
    page_id,
    json={
    "headings": [
        {
            "heading": "This is a monkey",
            "image": {
                "image_url": "https://raw.githubusercontent.com/SurveyMonkey/public_api_docs/master/images/presentation.png"
            }
        }
    ],
    "position": 4,
    "family": "presentation",
    "subtype": "descriptive_text"
}

)
Error:

![selection_003](https://user-images.githubusercontent.com/14146528/27973466-0b805530-6352-11e7-9752-0bbbe7c855fe.png)

**Comment by andrewkshim** [comment]
@akshay-vaidya I'm not as familiar with the SurveyMonkey API as I used to be, but taking a look at the documentation it looks like the attribute you called `"image_url"` should be renamed to `"url"`.

Screenshot of the relevant SurveyMonkey API docs:

![screen shot 2017-07-07 at 12 30 39 pm](https://user-images.githubusercontent.com/1403410/27973853-5d52e31a-6310-11e7-92ae-c21c24988942.png)

Since this isn't related to `surveymonty` itself, I'm going to mark this issue as closed. If you have any other questions related to the library, feel free to keep commenting in this issue.
